document.write( '<footer class=\"page-footer font-small pt-4\">\n' );
document.write( '\n' );
document.write( '    <!-- Footer Elements -->\n' );
document.write( '    <div class=\"container\">\n' );
document.write( '\n' );
document.write( '        <!-- Social buttons -->\n' );
document.write( '        <ul class=\"list-unstyled list-inline text-center\">\n' );
document.write( '            <li class=\"list-inline-item\">\n' );
document.write( '                <a href=\"#\" class=\"btn-floating btn-fb mx-1\">\n' );
document.write( '                    <i class=\"fab fa-facebook-f fa-2x\"> </i>\n' );
document.write( '                </a>\n' );
document.write( '            </li>\n' );
document.write( '            <li class=\"list-inline-item\">\n' );
document.write( '                <a href=\"#\" class=\"btn-floating btn-tw mx-1\">\n' );
document.write( '                    <i class=\"fab fa-twitter fa-2x\"> </i>\n' );
document.write( '                </a>\n' );
document.write( '            </li>\n' );
document.write( '            <li class=\"list-inline-item\">\n' );
document.write( '                <a href=\"#\" class=\"btn-floating btn-gplus mx-1\">\n' );
document.write( '                    <i class=\"fab fa-google-plus-g fa-2x\"> </i>\n' );
document.write( '                </a>\n' );
document.write( '            </li>\n' );
document.write( '            <li class=\"list-inline-item\">\n' );
document.write( '                <a href=\"#\" class=\"btn-floating btn-gplus mx-1\">\n' );
document.write( '                    <i class=\"fab fa-instagram fa-2x\"></i>\n' );
document.write( '                </a>\n' );
document.write( '            </li>\n' );
document.write( '        </ul>\n' );
document.write( '        <!-- Social buttons -->\n' );
document.write( '\n' );
document.write( '    </div>\n' );
document.write( '    <!-- Footer Elements -->\n' );
document.write( '\n' );
document.write( '    <!-- Copyright -->\n' );
document.write( '    <div class=\"footer-copyright text-center py-3\">© 2021 Copyright: Chocolush</div>\n' );
document.write( '    <!-- Copyright -->\n' );
document.write( '\n' );
document.write( '</footer>\n' );
